# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'faker', '~> 2.15', '>= 2.15.1'

gem 'ruby2d', '~> 0.9.4'

gem 'minitest', '~> 5.14', '>= 5.14.3'